In [1]:
import numpy as np
import pandas as pd
import nltk

In [2]:
from nltk.corpus import inaugural
print(inaugural.fileids())

['1789-Washington.txt', '1793-Washington.txt', '1797-Adams.txt', '1801-Jefferson.txt', '1805-Jefferson.txt', '1809-Madison.txt', '1813-Madison.txt', '1817-Monroe.txt', '1821-Monroe.txt', '1825-Adams.txt', '1829-Jackson.txt', '1833-Jackson.txt', '1837-VanBuren.txt', '1841-Harrison.txt', '1845-Polk.txt', '1849-Taylor.txt', '1853-Pierce.txt', '1857-Buchanan.txt', '1861-Lincoln.txt', '1865-Lincoln.txt', '1869-Grant.txt', '1873-Grant.txt', '1877-Hayes.txt', '1881-Garfield.txt', '1885-Cleveland.txt', '1889-Harrison.txt', '1893-Cleveland.txt', '1897-McKinley.txt', '1901-McKinley.txt', '1905-Roosevelt.txt', '1909-Taft.txt', '1913-Wilson.txt', '1917-Wilson.txt', '1921-Harding.txt', '1925-Coolidge.txt', '1929-Hoover.txt', '1933-Roosevelt.txt', '1937-Roosevelt.txt', '1941-Roosevelt.txt', '1945-Roosevelt.txt', '1949-Truman.txt', '1953-Eisenhower.txt', '1957-Eisenhower.txt', '1961-Kennedy.txt', '1965-Johnson.txt', '1969-Nixon.txt', '1973-Nixon.txt', '1977-Carter.txt', '1981-Reagan.txt', '1985-Reagan.txt', '1989-Bush.txt', '1993-Clinton.txt', '1997-Clinton.txt', '2001-Bush.txt', '2005-Bush.txt', '2009-Obama.txt']

In [14]:
len(inaugural.raw(inaugural.fileids()[0]))

8619

In [33]:
inaug = pd.DataFrame(columns=['year','name','length','words','sents'])

for fileid in inaugural.fileids():
    
    #word characteristics
    length = len(inaugural.raw(fileid))
    words = len(inaugural.words(fileid))
    sents = len(inaugural.sents(fileid))
    vocab = len(set(word.lower() for word in inaugural.words(fileid)))
    
    #append word characteristics
    inaug = inaug.append({'year':fileid[:4], 'name':fileid[5:-4],
                          'length':length, 'words':words, 'sents':sents, 'vocab':vocab},
                         ignore_index=True)
inaug

    year        name length words sents   vocab
0   1789  Washington   8619  1538    24   604.0
1   1793  Washington    791   147     4    95.0
2   1797       Adams  13877  2585    37   803.0
3   1801   Jefferson  10137  1935    42   687.0
4   1805   Jefferson  12908  2384    45   783.0
5   1809     Madison   7001  1265    21   526.0
6   1813     Madison   7157  1304    33   524.0
7   1817      Monroe  19887  3693   122   987.0
8   1821      Monroe  26326  4909   129  1213.0
9   1825       Adams  17741  3150    74   972.0
10  1829     Jackson   6817  1208    25   504.0
11  1833     Jackson   7058  1267    30   482.0
12  1837    VanBuren  23417  4171    95  1267.0
13  1841    Harrison  49700  9165   210  1813.0
14  1845        Polk  28716  5196   153  1267.0
15  1849      Taylor   6605  1182    22   488.0
16  1853      Pierce  20081  3657   104  1124.0
17  1857    Buchanan  16815  3098    89   902.0
18  1861     Lincoln  21017  4005   138  1019.0
19  1865     Lincoln   3926   785    27   345.0
20  1869       Grant   6503  1239    41   474.0
21  1873       Grant   7734  1478    44   530.0
22  1877       Hayes  14938  2724    59   808.0
23  1881    Garfield  17767  3239   112   981.0
24  1885   Cleveland  10145  1828    44   650.0
25  1889    Harrison  26179  4750   157  1313.0
26  1893   Cleveland  12349  2153    58   799.0
27  1897    McKinley  23659  4371   130  1199.0
28  1901    McKinley  13408  2450   100   828.0
29  1905   Roosevelt   5568  1091    33   388.0
30  1909        Taft  32164  5846   159  1385.0
31  1913      Wilson   9563  1905    68   637.0
32  1917      Wilson   8395  1656    60   529.0
33  1921     Harding  20298  3756   149  1126.0
34  1925    Coolidge  23949  4442   197  1164.0
35  1929      Hoover  21764  3890   158   998.0
36  1933   Roosevelt  10903  2063    85   715.0
37  1937   Roosevelt  10607  2019    96   698.0
38  1941   Roosevelt   7571  1536    68   502.0
39  1945   Roosevelt   3039   637    26   270.0
40  1949      Truman  13679  2528   116   745.0
41  1953  Eisenhower  13955  2775   123   864.0
42  1957  Eisenhower   9190  1917    92   592.0
43  1961     Kennedy   7618  1546    52   546.0
44  1965     Johnson   8193  1715    94   538.0
45  1969       Nixon  11624  2425   106   714.0
46  1973       Nixon   9991  2028    69   516.0
47  1977      Carter   6873  1380    53   504.0
48  1981      Reagan  13735  2801   127   855.0
49  1985      Reagan  14561  2946   126   876.0
50  1989        Bush  12523  2713   145   754.0
51  1993     Clinton   9114  1855    81   604.0
52  1997     Clinton  12250  2462   112   727.0
53  2001        Bush   9053  1825    97   593.0
54  2005        Bush  12018  2376    95   742.0
55  2009       Obama  13439  2726   112   900.0