In [1]:
import numpy as np
import pandas as pd
import nltk

In [2]:
from nltk.corpus import inaugural
print(inaugural.fileids())

['1789-Washington.txt', '1793-Washington.txt', '1797-Adams.txt', '1801-Jefferson.txt', '1805-Jefferson.txt', '1809-Madison.txt', '1813-Madison.txt', '1817-Monroe.txt', '1821-Monroe.txt', '1825-Adams.txt', '1829-Jackson.txt', '1833-Jackson.txt', '1837-VanBuren.txt', '1841-Harrison.txt', '1845-Polk.txt', '1849-Taylor.txt', '1853-Pierce.txt', '1857-Buchanan.txt', '1861-Lincoln.txt', '1865-Lincoln.txt', '1869-Grant.txt', '1873-Grant.txt', '1877-Hayes.txt', '1881-Garfield.txt', '1885-Cleveland.txt', '1889-Harrison.txt', '1893-Cleveland.txt', '1897-McKinley.txt', '1901-McKinley.txt', '1905-Roosevelt.txt', '1909-Taft.txt', '1913-Wilson.txt', '1917-Wilson.txt', '1921-Harding.txt', '1925-Coolidge.txt', '1929-Hoover.txt', '1933-Roosevelt.txt', '1937-Roosevelt.txt', '1941-Roosevelt.txt', '1945-Roosevelt.txt', '1949-Truman.txt', '1953-Eisenhower.txt', '1957-Eisenhower.txt', '1961-Kennedy.txt', '1965-Johnson.txt', '1969-Nixon.txt', '1973-Nixon.txt', '1977-Carter.txt', '1981-Reagan.txt', '1985-Reagan.txt', '1989-Bush.txt', '1993-Clinton.txt', '1997-Clinton.txt', '2001-Bush.txt', '2005-Bush.txt', '2009-Obama.txt']

In [3]:
len(inaugural.raw(inaugural.fileids()[0]))

8619

In [191]:
inaug = pd.DataFrame(columns=['year','name','length','words','sents'])

for fileid in inaugural.fileids():
    
    #word characteristics
    length = len(inaugural.raw(fileid))
    words = len(inaugural.words(fileid))
    sents = len(inaugural.sents(fileid))
    vocab = len(set(word.lower() for word in inaugural.words(fileid)))
    
    #append word characteristics
    inaug = inaug.append({'year':fileid[:4], 'name':fileid[5:-4],
                          'length':length, 'words':words, 'sents':sents, 'vocab':vocab},
                         ignore_index=True)
inaug

    year        name length words sents   vocab
0   1789  Washington   8619  1538    24   604.0
1   1793  Washington    791   147     4    95.0
2   1797       Adams  13877  2585    37   803.0
3   1801   Jefferson  10137  1935    42   687.0
4   1805   Jefferson  12908  2384    45   783.0
5   1809     Madison   7001  1265    21   526.0
6   1813     Madison   7157  1304    33   524.0
7   1817      Monroe  19887  3693   122   987.0
8   1821      Monroe  26326  4909   129  1213.0
9   1825       Adams  17741  3150    74   972.0
10  1829     Jackson   6817  1208    25   504.0
11  1833     Jackson   7058  1267    30   482.0
12  1837    VanBuren  23417  4171    95  1267.0
13  1841    Harrison  49700  9165   210  1813.0
14  1845        Polk  28716  5196   153  1267.0
15  1849      Taylor   6605  1182    22   488.0
16  1853      Pierce  20081  3657   104  1124.0
17  1857    Buchanan  16815  3098    89   902.0
18  1861     Lincoln  21017  4005   138  1019.0
19  1865     Lincoln   3926   785    27   345.0
20  1869       Grant   6503  1239    41   474.0
21  1873       Grant   7734  1478    44   530.0
22  1877       Hayes  14938  2724    59   808.0
23  1881    Garfield  17767  3239   112   981.0
24  1885   Cleveland  10145  1828    44   650.0
25  1889    Harrison  26179  4750   157  1313.0
26  1893   Cleveland  12349  2153    58   799.0
27  1897    McKinley  23659  4371   130  1199.0
28  1901    McKinley  13408  2450   100   828.0
29  1905   Roosevelt   5568  1091    33   388.0
30  1909        Taft  32164  5846   159  1385.0
31  1913      Wilson   9563  1905    68   637.0
32  1917      Wilson   8395  1656    60   529.0
33  1921     Harding  20298  3756   149  1126.0
34  1925    Coolidge  23949  4442   197  1164.0
35  1929      Hoover  21764  3890   158   998.0
36  1933   Roosevelt  10903  2063    85   715.0
37  1937   Roosevelt  10607  2019    96   698.0
38  1941   Roosevelt   7571  1536    68   502.0
39  1945   Roosevelt   3039   637    26   270.0
40  1949      Truman  13679  2528   116   745.0
41  1953  Eisenhower  13955  2775   123   864.0
42  1957  Eisenhower   9190  1917    92   592.0
43  1961     Kennedy   7618  1546    52   546.0
44  1965     Johnson   8193  1715    94   538.0
45  1969       Nixon  11624  2425   106   714.0
46  1973       Nixon   9991  2028    69   516.0
47  1977      Carter   6873  1380    53   504.0
48  1981      Reagan  13735  2801   127   855.0
49  1985      Reagan  14561  2946   126   876.0
50  1989        Bush  12523  2713   145   754.0
51  1993     Clinton   9114  1855    81   604.0
52  1997     Clinton  12250  2462   112   727.0
53  2001        Bush   9053  1825    97   593.0
54  2005        Bush  12018  2376    95   742.0
55  2009       Obama  13439  2726   112   900.0

In [192]:
inaug.dtypes

year       object
name       object
length     object
words      object
sents      object
vocab     float64
dtype: object

In [193]:
def convert_all_numcol_to_int(df):
    for col in df.columns:
        try: df[col] = df[col].astype(int)
        except: continue
    return(df)

In [194]:
inaug = convert_all_numcol_to_int(inaug)
inaug

    year        name  length  words  sents  vocab
0   1789  Washington    8619   1538     24    604
1   1793  Washington     791    147      4     95
2   1797       Adams   13877   2585     37    803
3   1801   Jefferson   10137   1935     42    687
4   1805   Jefferson   12908   2384     45    783
5   1809     Madison    7001   1265     21    526
6   1813     Madison    7157   1304     33    524
7   1817      Monroe   19887   3693    122    987
8   1821      Monroe   26326   4909    129   1213
9   1825       Adams   17741   3150     74    972
10  1829     Jackson    6817   1208     25    504
11  1833     Jackson    7058   1267     30    482
12  1837    VanBuren   23417   4171     95   1267
13  1841    Harrison   49700   9165    210   1813
14  1845        Polk   28716   5196    153   1267
15  1849      Taylor    6605   1182     22    488
16  1853      Pierce   20081   3657    104   1124
17  1857    Buchanan   16815   3098     89    902
18  1861     Lincoln   21017   4005    138   1019
19  1865     Lincoln    3926    785     27    345
20  1869       Grant    6503   1239     41    474
21  1873       Grant    7734   1478     44    530
22  1877       Hayes   14938   2724     59    808
23  1881    Garfield   17767   3239    112    981
24  1885   Cleveland   10145   1828     44    650
25  1889    Harrison   26179   4750    157   1313
26  1893   Cleveland   12349   2153     58    799
27  1897    McKinley   23659   4371    130   1199
28  1901    McKinley   13408   2450    100    828
29  1905   Roosevelt    5568   1091     33    388
30  1909        Taft   32164   5846    159   1385
31  1913      Wilson    9563   1905     68    637
32  1917      Wilson    8395   1656     60    529
33  1921     Harding   20298   3756    149   1126
34  1925    Coolidge   23949   4442    197   1164
35  1929      Hoover   21764   3890    158    998
36  1933   Roosevelt   10903   2063     85    715
37  1937   Roosevelt   10607   2019     96    698
38  1941   Roosevelt    7571   1536     68    502
39  1945   Roosevelt    3039    637     26    270
40  1949      Truman   13679   2528    116    745
41  1953  Eisenhower   13955   2775    123    864
42  1957  Eisenhower    9190   1917     92    592
43  1961     Kennedy    7618   1546     52    546
44  1965     Johnson    8193   1715     94    538
45  1969       Nixon   11624   2425    106    714
46  1973       Nixon    9991   2028     69    516
47  1977      Carter    6873   1380     53    504
48  1981      Reagan   13735   2801    127    855
49  1985      Reagan   14561   2946    126    876
50  1989        Bush   12523   2713    145    754
51  1993     Clinton    9114   1855     81    604
52  1997     Clinton   12250   2462    112    727
53  2001        Bush    9053   1825     97    593
54  2005        Bush   12018   2376     95    742
55  2009       Obama   13439   2726    112    900

In [195]:
inaug['awl'] = inaug.length/inaug.words
inaug['asl'] = inaug.length/inaug.sents
inaug['awps'] = inaug.words/inaug.sents
inaug['avps'] = inaug.vocab/inaug.sents
inaug['awpv'] = inaug.words/inaug.vocab
inaug

,year,name,length,words,sents,vocab,awl,asl,awps,avps,awpv
0,1789,Washington,8619,1538,24,604,5.604031,359.125000,64.083333,25.166667,2.546358
1,1793,Washington,791,147,4,95,5.380952,197.750000,36.750000,23.750000,1.547368
2,1797,Adams,13877,2585,37,803,5.368279,375.054054,69.864865,21.702703,3.219178
3,1801,Jefferson,10137,1935,42,687,5.238760,241.357143,46.071429,16.357143,2.816594
4,1805,Jefferson,12908,2384,45,783,5.414430,286.844444,52.977778,17.400000,3.044700
5,1809,Madison,7001,1265,21,526,5.534387,333.380952,60.238095,25.047619,2.404943
6,1813,Madison,7157,1304,33,524,5.488497,216.878788,39.515152,15.878788,2.488550
7,1817,Monroe,19887,3693,122,987,5.385053,163.008197,30.270492,8.090164,3.741641
8,1821,Monroe,26326,4909,129,1213,5.362803,204.077519,38.054264,9.403101,4.046991
9,1825,Adams,17741,3150,74,972,5.632063,239.743243,42.567568,13.135135,3.240741
10,1829,Jackson,6817,1208,25,504,5.643212,272.680000,48.320000,20.160000,2.396825
11,1833,Jackson,7058,1267,30,482,5.570639,235.266667,42.233333,16.066667,2.628631
12,1837,VanBuren,23417,4171,95,1267,5.614241,246.494737,43.905263,13.336842,3.292028
13,1841,Harrison,49700,9165,210,1813,5.422804,236.666667,43.642857,8.633333,5.055157
14,1845,Polk,28716,5196,153,1267,5.526559,187.686275,33.960784,8.281046,4.101026
15,1849,Taylor,6605,1182,22,488,5.587986,300.227273,53.727273,22.181818,2.422131
16,1853,Pierce,20081,3657,104,1124,5.491113,193.086538,35.163462,10.807692,3.253559
17,1857,Buchanan,16815,3098,89,902,5.427695,188.932584,34.808989,10.134831,3.434590
18,1861,Lincoln,21017,4005,138,1019,5.247690,152.297101,29.021739,7.384058,3.930324
19,1865,Lincoln,3926,785,27,345,5.001274,145.407407,29.074074,12.777778,2.275362
20,1869,Grant,6503,1239,41,474,5.248588,158.609756,30.219512,11.560976,2.613924
21,1873,Grant,7734,1478,44,530,5.232747,175.772727,33.590909,12.045455,2.788679
22,1877,Hayes,14938,2724,59,808,5.483847,253.186441,46.169492,13.694915,3.371287
23,1881,Garfield,17767,3239,112,981,5.485335,158.633929,28.919643,8.758929,3.301733
24,1885,Cleveland,10145,1828,44,650,5.549781,230.568182,41.545455,14.772727,2.812308
25,1889,Harrison,26179,4750,157,1313,5.511368,166.745223,30.254777,8.363057,3.617669
26,1893,Cleveland,12349,2153,58,799,5.735718,212.913793,37.120690,13.775862,2.694618
27,1897,McKinley,23659,4371,130,1199,5.412720,181.992308,33.623077,9.223077,3.645538
28,1901,McKinley,13408,2450,100,828,5.472653,134.080000,24.500000,8.280000,2.958937
29,1905,Roosevelt,5568,1091,33,388,5.103575,168.727273,33.060606,11.757576,2.811856
30,1909,Taft,32164,5846,159,1385,5.501882,202.289308,36.767296,8.710692,4.220939
31,1913,Wilson,9563,1905,68,637,5.019948,140.632353,28.014706,9.367647,2.990581
32,1917,Wilson,8395,1656,60,529,5.069444,139.916667,27.600000,8.816667,3.130435
33,1921,Harding,20298,3756,149,1126,5.404153,136.228188,25.208054,7.557047,3.335702
34,1925,Coolidge,23949,4442,197,1164,5.391490,121.568528,22.548223,5.908629,3.816151
35,1929,Hoover,21764,3890,158,998,5.594859,137.746835,24.620253,6.316456,3.897796
36,1933,Roosevelt,10903,2063,85,715,5.285022,128.270588,24.270588,8.411765,2.885315
37,1937,Roosevelt,10607,2019,96,698,5.253591,110.489583,21.031250,7.270833,2.892550
38,1941,Roosevelt,7571,1536,68,502,4.929036,111.338235,22.588235,7.382353,3.059761
39,1945,Roosevelt,3039,637,26,270,4.770801,116.884615,24.500000,10.384615,2.359259
40,1949,Truman,13679,2528,116,745,5.410997,117.922414,21.793103,6.422414,3.393289
41,1953,Eisenhower,13955,2775,123,864,5.028829,113.455285,22.560976,7.024390,3.211806
42,1957,Eisenhower,9190,1917,92,592,4.793949,99.891304,20.836957,6.434783,3.238176
43,1961,Kennedy,7618,1546,52,546,4.927555,146.500000,29.730769,10.500000,2.831502
44,1965,Johnson,8193,1715,94,538,4.777259,87.159574,18.244681,5.723404,3.187732
45,1969,Nixon,11624,2425,106,714,4.793402,109.660377,22.877358,6.735849,3.396359
46,1973,Nixon,9991,2028,69,516,4.926529,144.797101,29.391304,7.478261,3.930233
47,1977,Carter,6873,1380,53,504,4.980435,129.679245,26.037736,9.509434,2.738095
48,1981,Reagan,13735,2801,127,855,4.903606,108.149606,22.055118,6.732283,3.276023
49,1985,Reagan,14561,2946,126,876,4.942634,115.563492,23.380952,6.952381,3.363014
50,1989,Bush,12523,2713,145,754,4.615923,86.365517,18.710345,5.200000,3.598143
51,1993,Clinton,9114,1855,81,604,4.913208,112.518519,22.901235,7.456790,3.071192
52,1997,Clinton,12250,2462,112,727,4.975630,109.375000,21.982143,6.491071,3.386520
53,2001,Bush,9053,1825,97,593,4.960548,93.329897,18.814433,6.113402,3.077572
54,2005,Bush,12018,2376,95,742,5.058081,126.505263,25.010526,7.810526,3.202156
55,2009,Obama,13439,2726,112,900,4.929934,119.991071,24.339286,8.035714,3.028889

In [196]:
inaug.index

RangeIndex(start=0, stop=56, step=1)

In [197]:
inaug['in_number'] = ''
president = 0
for i in inaug.index[1:]:
    if inaug['name'][i]!=inaug['name'][i-1]:
        president+=1
        inaug['in_number'][i] = president
        
    else:
        inaug['in_number'][i] = president
        inaug['in_number'][i-1] = president
        inaug['year'][i] = np.nan

C:\Users\zafri\Anaconda3\lib\site-packages\ipykernel\__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\zafri\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\zafri\Anaconda3\lib\site-packages\ipykernel\__main__.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\zafri\Anaconda3\lib\site-packages\pandas\core\indexing.py:179: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\zafri\Anaconda3\lib\site-packages\ipykernel\__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [198]:
inaug

,year,name,length,words,sents,vocab,awl,asl,awps,avps,awpv,in_number
0,1789.0,Washington,8619,1538,24,604,5.604031,359.125000,64.083333,25.166667,2.546358,0
1,NaN,Washington,791,147,4,95,5.380952,197.750000,36.750000,23.750000,1.547368,0
2,1797.0,Adams,13877,2585,37,803,5.368279,375.054054,69.864865,21.702703,3.219178,1
3,1801.0,Jefferson,10137,1935,42,687,5.238760,241.357143,46.071429,16.357143,2.816594,2
4,NaN,Jefferson,12908,2384,45,783,5.414430,286.844444,52.977778,17.400000,3.044700,2
5,1809.0,Madison,7001,1265,21,526,5.534387,333.380952,60.238095,25.047619,2.404943,3
6,NaN,Madison,7157,1304,33,524,5.488497,216.878788,39.515152,15.878788,2.488550,3
7,1817.0,Monroe,19887,3693,122,987,5.385053,163.008197,30.270492,8.090164,3.741641,4
8,NaN,Monroe,26326,4909,129,1213,5.362803,204.077519,38.054264,9.403101,4.046991,4
9,1825.0,Adams,17741,3150,74,972,5.632063,239.743243,42.567568,13.135135,3.240741,5
10,1829.0,Jackson,6817,1208,25,504,5.643212,272.680000,48.320000,20.160000,2.396825,6
11,NaN,Jackson,7058,1267,30,482,5.570639,235.266667,42.233333,16.066667,2.628631,6
12,1837.0,VanBuren,23417,4171,95,1267,5.614241,246.494737,43.905263,13.336842,3.292028,7
13,1841.0,Harrison,49700,9165,210,1813,5.422804,236.666667,43.642857,8.633333,5.055157,8
14,1845.0,Polk,28716,5196,153,1267,5.526559,187.686275,33.960784,8.281046,4.101026,9
15,1849.0,Taylor,6605,1182,22,488,5.587986,300.227273,53.727273,22.181818,2.422131,10
16,1853.0,Pierce,20081,3657,104,1124,5.491113,193.086538,35.163462,10.807692,3.253559,11
17,1857.0,Buchanan,16815,3098,89,902,5.427695,188.932584,34.808989,10.134831,3.434590,12
18,1861.0,Lincoln,21017,4005,138,1019,5.247690,152.297101,29.021739,7.384058,3.930324,13
19,NaN,Lincoln,3926,785,27,345,5.001274,145.407407,29.074074,12.777778,2.275362,13
20,1869.0,Grant,6503,1239,41,474,5.248588,158.609756,30.219512,11.560976,2.613924,14
21,NaN,Grant,7734,1478,44,530,5.232747,175.772727,33.590909,12.045455,2.788679,14
22,1877.0,Hayes,14938,2724,59,808,5.483847,253.186441,46.169492,13.694915,3.371287,15
23,1881.0,Garfield,17767,3239,112,981,5.485335,158.633929,28.919643,8.758929,3.301733,16
24,1885.0,Cleveland,10145,1828,44,650,5.549781,230.568182,41.545455,14.772727,2.812308,17
25,1889.0,Harrison,26179,4750,157,1313,5.511368,166.745223,30.254777,8.363057,3.617669,18
26,1893.0,Cleveland,12349,2153,58,799,5.735718,212.913793,37.120690,13.775862,2.694618,19
27,1897.0,McKinley,23659,4371,130,1199,5.412720,181.992308,33.623077,9.223077,3.645538,20
28,NaN,McKinley,13408,2450,100,828,5.472653,134.080000,24.500000,8.280000,2.958937,20
29,1905.0,Roosevelt,5568,1091,33,388,5.103575,168.727273,33.060606,11.757576,2.811856,21
30,1909.0,Taft,32164,5846,159,1385,5.501882,202.289308,36.767296,8.710692,4.220939,22
31,1913.0,Wilson,9563,1905,68,637,5.019948,140.632353,28.014706,9.367647,2.990581,23
32,NaN,Wilson,8395,1656,60,529,5.069444,139.916667,27.600000,8.816667,3.130435,23
33,1921.0,Harding,20298,3756,149,1126,5.404153,136.228188,25.208054,7.557047,3.335702,24
34,1925.0,Coolidge,23949,4442,197,1164,5.391490,121.568528,22.548223,5.908629,3.816151,25
35,1929.0,Hoover,21764,3890,158,998,5.594859,137.746835,24.620253,6.316456,3.897796,26
36,1933.0,Roosevelt,10903,2063,85,715,5.285022,128.270588,24.270588,8.411765,2.885315,27
37,NaN,Roosevelt,10607,2019,96,698,5.253591,110.489583,21.031250,7.270833,2.892550,27
38,NaN,Roosevelt,7571,1536,68,502,4.929036,111.338235,22.588235,7.382353,3.059761,27
39,NaN,Roosevelt,3039,637,26,270,4.770801,116.884615,24.500000,10.384615,2.359259,27
40,1949.0,Truman,13679,2528,116,745,5.410997,117.922414,21.793103,6.422414,3.393289,28
41,1953.0,Eisenhower,13955,2775,123,864,5.028829,113.455285,22.560976,7.024390,3.211806,29
42,NaN,Eisenhower,9190,1917,92,592,4.793949,99.891304,20.836957,6.434783,3.238176,29
43,1961.0,Kennedy,7618,1546,52,546,4.927555,146.500000,29.730769,10.500000,2.831502,30
44,1965.0,Johnson,8193,1715,94,538,4.777259,87.159574,18.244681,5.723404,3.187732,31
45,1969.0,Nixon,11624,2425,106,714,4.793402,109.660377,22.877358,6.735849,3.396359,32
46,NaN,Nixon,9991,2028,69,516,4.926529,144.797101,29.391304,7.478261,3.930233,32
47,1977.0,Carter,6873,1380,53,504,4.980435,129.679245,26.037736,9.509434,2.738095,33
48,1981.0,Reagan,13735,2801,127,855,4.903606,108.149606,22.055118,6.732283,3.276023,34
49,NaN,Reagan,14561,2946,126,876,4.942634,115.563492,23.380952,6.952381,3.363014,34
50,1989.0,Bush,12523,2713,145,754,4.615923,86.365517,18.710345,5.200000,3.598143,35
51,1993.0,Clinton,9114,1855,81,604,4.913208,112.518519,22.901235,7.456790,3.071192,36
52,NaN,Clinton,12250,2462,112,727,4.975630,109.375000,21.982143,6.491071,3.386520,36
53,2001.0,Bush,9053,1825,97,593,4.960548,93.329897,18.814433,6.113402,3.077572,37
54,NaN,Bush,12018,2376,95,742,5.058081,126.505263,25.010526,7.810526,3.202156,37
55,2009.0,Obama,13439,2726,112,900,4.929934,119.991071,24.339286,8.035714,3.028889,38

In [199]:
inaug = inaug.groupby(['in_number'], as_index=False).mean()

In [200]:
inaug

,in_number,year,length,words,sents,vocab,awl,asl,awps,avps,awpv
0,0,1789.0,4705.0,842.50,14.00,349.50,5.492492,278.437500,50.416667,24.458333,2.046863
1,1,1797.0,13877.0,2585.00,37.00,803.00,5.368279,375.054054,69.864865,21.702703,3.219178
2,2,1801.0,11522.5,2159.50,43.50,735.00,5.326595,264.100794,49.524603,16.878571,2.930647
3,3,1809.0,7079.0,1284.50,27.00,525.00,5.511442,275.129870,49.876623,20.463203,2.446746
4,4,1817.0,23106.5,4301.00,125.50,1100.00,5.373928,183.542858,34.162378,8.746632,3.894316
5,5,1825.0,17741.0,3150.00,74.00,972.00,5.632063,239.743243,42.567568,13.135135,3.240741
6,6,1829.0,6937.5,1237.50,27.50,493.00,5.606926,253.973333,45.276667,18.113333,2.512728
7,7,1837.0,23417.0,4171.00,95.00,1267.00,5.614241,246.494737,43.905263,13.336842,3.292028
8,8,1841.0,49700.0,9165.00,210.00,1813.00,5.422804,236.666667,43.642857,8.633333,5.055157
9,9,1845.0,28716.0,5196.00,153.00,1267.00,5.526559,187.686275,33.960784,8.281046,4.101026
10,10,1849.0,6605.0,1182.00,22.00,488.00,5.587986,300.227273,53.727273,22.181818,2.422131
11,11,1853.0,20081.0,3657.00,104.00,1124.00,5.491113,193.086538,35.163462,10.807692,3.253559
12,12,1857.0,16815.0,3098.00,89.00,902.00,5.427695,188.932584,34.808989,10.134831,3.434590
13,13,1861.0,12471.5,2395.00,82.50,682.00,5.124482,148.852254,29.047907,10.080918,3.102843
14,14,1869.0,7118.5,1358.50,42.50,502.00,5.240667,167.191242,31.905211,11.803215,2.701302
15,15,1877.0,14938.0,2724.00,59.00,808.00,5.483847,253.186441,46.169492,13.694915,3.371287
16,16,1881.0,17767.0,3239.00,112.00,981.00,5.485335,158.633929,28.919643,8.758929,3.301733
17,17,1885.0,10145.0,1828.00,44.00,650.00,5.549781,230.568182,41.545455,14.772727,2.812308
18,18,1889.0,26179.0,4750.00,157.00,1313.00,5.511368,166.745223,30.254777,8.363057,3.617669
19,19,1893.0,12349.0,2153.00,58.00,799.00,5.735718,212.913793,37.120690,13.775862,2.694618
20,20,1897.0,18533.5,3410.50,115.00,1013.50,5.442687,158.036154,29.061538,8.751538,3.302238
21,21,1905.0,5568.0,1091.00,33.00,388.00,5.103575,168.727273,33.060606,11.757576,2.811856
22,22,1909.0,32164.0,5846.00,159.00,1385.00,5.501882,202.289308,36.767296,8.710692,4.220939
23,23,1913.0,8979.0,1780.50,64.00,583.00,5.044696,140.274510,27.807353,9.092157,3.060508
24,24,1921.0,20298.0,3756.00,149.00,1126.00,5.404153,136.228188,25.208054,7.557047,3.335702
25,25,1925.0,23949.0,4442.00,197.00,1164.00,5.391490,121.568528,22.548223,5.908629,3.816151
26,26,1929.0,21764.0,3890.00,158.00,998.00,5.594859,137.746835,24.620253,6.316456,3.897796
27,27,1933.0,8030.0,1563.75,68.75,546.25,5.059612,116.745756,23.097518,8.362392,2.799221
28,28,1949.0,13679.0,2528.00,116.00,745.00,5.410997,117.922414,21.793103,6.422414,3.393289
29,29,1953.0,11572.5,2346.00,107.50,728.00,4.911389,106.673294,21.698966,6.729586,3.224991
30,30,1961.0,7618.0,1546.00,52.00,546.00,4.927555,146.500000,29.730769,10.500000,2.831502
31,31,1965.0,8193.0,1715.00,94.00,538.00,4.777259,87.159574,18.244681,5.723404,3.187732
32,32,1969.0,10807.5,2226.50,87.50,615.00,4.859965,127.228739,26.134331,7.107055,3.663296
33,33,1977.0,6873.0,1380.00,53.00,504.00,4.980435,129.679245,26.037736,9.509434,2.738095
34,34,1981.0,14148.0,2873.50,126.50,865.50,4.923120,111.856549,22.718035,6.842332,3.319519
35,35,1989.0,12523.0,2713.00,145.00,754.00,4.615923,86.365517,18.710345,5.200000,3.598143
36,36,1993.0,10682.0,2158.50,96.50,665.50,4.944419,110.946759,22.441689,6.973931,3.228856
37,37,2001.0,10535.5,2100.50,96.00,667.50,5.009314,109.917580,21.912480,6.961964,3.139864
38,38,2009.0,13439.0,2726.00,112.00,900.00,4.929934,119.991071,24.339286,8.035714,3.028889

### Get IQ Data

In [209]:
iqs = pd.read_excel('presidents_iqs.xlsx', sheetname='data')
iqs.columns = [col.lower().replace(' ','_') for col in iqs.columns]
iqs = iqs.rename(columns={'iq_(corrected_for_data_reliability,_ages_18–26)[9]':'iq1',
                          'other_iq_estimates':'iq2','unnamed:_6':'iq3','name':'full_name'})
iqs.head()

,full_name,political_party,lifespan,time_in_office,iq1,iq2,iq3
0,George Washington,None/Federalist,1732–1799,1789–1797,130.0,NaN,NaN
1,John Adams,Federalist,1735–1826,1797–1801,145.0,NaN,NaN
2,Thomas Jefferson,Democratic-Republican,1743–1826,1801–1809,150.0,NaN,NaN
3,James Madison,Democratic-Republican,1751–1836,1809–1817,150.0,NaN,NaN
4,James Monroe,Democratic-Republican,1758–1831,1817–1825,128.6,NaN,NaN

d2 = pd.DataFrame(d1.ticker.str.split().tolist(), 
   .....:                   columns="symbol date price".split())

In [210]:
iqs.dtypes

full_name           object
political_party     object
lifespan            object
time_in_office      object
iq1                float64
iq2                float64
iq3                float64
dtype: object

In [211]:
#iqs['Time in Office'] = iqs['Time in Office'].astype(str)
#iqs['time_in_office'] = iqs['time_in_office'].astype(str).apply(lambda s: (s.split('–'))[0])
iqs['office_start'] = iqs['time_in_office'].astype(str).apply(lambda s: (s.split('–'))[0])
iqs['office_end'] = iqs['time_in_office'].astype(str).apply(lambda s: (s.split('–'))[-1])
iqs = iqs.replace('present',np.nan)
iqs

,full_name,political_party,lifespan,time_in_office,iq1,iq2,iq3,office_start,office_end
0,George Washington,None/Federalist,1732–1799,1789–1797,130.0,NaN,NaN,1789,1797
1,John Adams,Federalist,1735–1826,1797–1801,145.0,NaN,NaN,1797,1801
2,Thomas Jefferson,Democratic-Republican,1743–1826,1801–1809,150.0,NaN,NaN,1801,1809
3,James Madison,Democratic-Republican,1751–1836,1809–1817,150.0,NaN,NaN,1809,1817
4,James Monroe,Democratic-Republican,1758–1831,1817–1825,128.6,NaN,NaN,1817,1825
5,John Quincy Adams,Democratic-Republican,1767–1848,1825–1829,165.0,NaN,NaN,1825,1829
6,Andrew Jackson,Democratic,1767–1845,1829–1837,135.0,NaN,NaN,1829,1837
7,Martin van Buren,Democratic,1782–1862,1837–1841,129.5,NaN,NaN,1837,1841
8,William Henry Harrison,Whig,1773–1841,1841,136.3,NaN,NaN,1841,1841
9,John Tyler,Whig,1790–1862,1841–1845,138.1,NaN,NaN,1841,1845
10,James Polk,Democratic,1795–1849,1845–1849,133.4,NaN,NaN,1845,1849
11,Zachary Taylor,Whig,1784–1850,1849–1850,129.8,NaN,NaN,1849,1850
12,Millard Fillmore,Whig,1800–1874,1850–1853,139.0,NaN,NaN,1850,1853
13,Franklin Pierce,Democratic,1804–1869,1853–1857,137.4,NaN,NaN,1853,1857
14,James Buchanan,Democratic,1791–1868,1857–1861,129.6,NaN,NaN,1857,1861
15,Abraham Lincoln,Republican,1809–1865,1861–1865,140.0,NaN,NaN,1861,1865
16,Andrew Johnson,National Union/Democratic,1808–1875,1865–1869,129.8,NaN,NaN,1865,1869
17,Ulysses Grant,Republican,1822–1885,1869–1877,120.0,NaN,NaN,1869,1877
18,Rutherford Hayes,Republican,1822–1893,1877–1881,136.3,NaN,NaN,1877,1881
19,James Garfield,Republican,1831–1881,1881,142.3,NaN,NaN,1881,1881
20,Chester Arthur,Republican,1829–1886,1881–1885,142.3,NaN,NaN,1881,1885
21,Grover Cleveland,Democratic,1837–1908,"1885–1889, 1893–1897",134.0,NaN,NaN,1885,1897
22,Benjamin Harrison,Republican,1833–1901,1889–1893,135.4,NaN,NaN,1889,1893
23,William McKinley,Republican,1843–1901,1897–1901,133.4,NaN,NaN,1897,1901
24,Theodore Roosevelt,Republican,1858–1919,1901–1909,143.0,NaN,NaN,1901,1909
25,William Howard Taft,Republican,1857–1930,1909–1913,129.5,NaN,NaN,1909,1913
26,Woodrow Wilson,Democratic,1856–1924,1913–1921,145.2,NaN,NaN,1913,1921
27,Warren Harding,Republican,1865–1923,1921–1923,129.9,NaN,NaN,1921,1923
28,Calvin Coolidge,Republican,1872–1933,1923–1929,131.6,NaN,NaN,1923,1929
29,Herbert Hoover,Republican,1874–1964,1929–1933,131.6,NaN,NaN,1929,1933
30,Franklin Roosevelt,Democratic,1882–1945,1933–1945,130.5,NaN,NaN,1933,1945
31,Harry Truman,Democratic,1884–1972,1945–1953,129.8,NaN,NaN,1945,1953
32,Dwight Eisenhower,Republican,1890–1969,1953–1961,135.1,NaN,NaN,1953,1961
33,John F. Kennedy,Democratic,1917–1963,1961–1963,149.8,119.0,NaN,1961,1963
34,Lyndon Johnson,Democratic,1908–1973,1963–1969,130.6,NaN,NaN,1963,1969
35,Richard Nixon,Republican,1913–1994,1969–1974,132.6,143.0,NaN,1969,1974
36,Gerald Ford,Republican,1913–2006,1974–1977,130.2,NaN,NaN,1974,1977
37,Jimmy Carter,Democratic,1924–present,1977–1981,153.0,NaN,NaN,1977,1981
38,Ronald Reagan,Republican,1911–2004,1981–1989,131.9,NaN,NaN,1981,1989
39,George H. W. Bush,Republican,1924–present,1989–1993,133.0,NaN,NaN,1989,1993
40,Bill Clinton,Democratic,1946–present,1993–2001,149.0,137.0,156.0,1993,2001
41,George W. Bush,Republican,1946–present,2001–2009,124.8,138.5,NaN,2001,2009
42,Barack Obama,Democratic,1961–present,2009–2017,145.0,130.0,NaN,2009,2017
43,Donald Trump,Republican,1946–present,2017–present,NaN,NaN,NaN,2017,NaN

In [212]:
#Get average iq
iqs['iq'] = iqs[['iq1','iq2','iq3']].mean(axis=1)

In [213]:
col_to_drop = ['political_party','lifespan','time_in_office','iq1','iq2','iq3']
for col in col_to_drop:
    iqs = iqs.drop(col,1)
iqs

                 full_name office_start office_end          iq
0        George Washington         1789       1797  130.000000
1               John Adams         1797       1801  145.000000
2         Thomas Jefferson         1801       1809  150.000000
3            James Madison         1809       1817  150.000000
4             James Monroe         1817       1825  128.600000
5        John Quincy Adams         1825       1829  165.000000
6           Andrew Jackson         1829       1837  135.000000
7         Martin van Buren         1837       1841  129.500000
8   William Henry Harrison         1841       1841  136.300000
9               John Tyler         1841       1845  138.100000
10              James Polk         1845       1849  133.400000
11          Zachary Taylor         1849       1850  129.800000
12        Millard Fillmore         1850       1853  139.000000
13         Franklin Pierce         1853       1857  137.400000
14          James Buchanan         1857       1861  129.600000
15         Abraham Lincoln         1861       1865  140.000000
16          Andrew Johnson         1865       1869  129.800000
17           Ulysses Grant         1869       1877  120.000000
18        Rutherford Hayes         1877       1881  136.300000
19          James Garfield         1881       1881  142.300000
20          Chester Arthur         1881       1885  142.300000
21        Grover Cleveland         1885       1897  134.000000
22       Benjamin Harrison         1889       1893  135.400000
23        William McKinley         1897       1901  133.400000
24      Theodore Roosevelt         1901       1909  143.000000
25     William Howard Taft         1909       1913  129.500000
26          Woodrow Wilson         1913       1921  145.200000
27          Warren Harding         1921       1923  129.900000
28         Calvin Coolidge         1923       1929  131.600000
29          Herbert Hoover         1929       1933  131.600000
30      Franklin Roosevelt         1933       1945  130.500000
31            Harry Truman         1945       1953  129.800000
32       Dwight Eisenhower         1953       1961  135.100000
33         John F. Kennedy         1961       1963  134.400000
34          Lyndon Johnson         1963       1969  130.600000
35           Richard Nixon         1969       1974  137.800000
36             Gerald Ford         1974       1977  130.200000
37            Jimmy Carter         1977       1981  153.000000
38           Ronald Reagan         1981       1989  131.900000
39       George H. W. Bush         1989       1993  133.000000
40            Bill Clinton         1993       2001  147.333333
41          George W. Bush         2001       2009  131.650000
42            Barack Obama         2009       2017  137.500000
43            Donald Trump         2017        NaN         NaN

iqs['name'] = iqs['full_name'].copy

In [214]:
iqs = iqs.replace('van Buren', 'VanBuren')
iqs['name'] = iqs.full_name.astype(str).apply(lambda s: (s.split())[-1])
iqs

                 full_name office_start office_end          iq        name
0        George Washington         1789       1797  130.000000  Washington
1               John Adams         1797       1801  145.000000       Adams
2         Thomas Jefferson         1801       1809  150.000000   Jefferson
3            James Madison         1809       1817  150.000000     Madison
4             James Monroe         1817       1825  128.600000      Monroe
5        John Quincy Adams         1825       1829  165.000000       Adams
6           Andrew Jackson         1829       1837  135.000000     Jackson
7         Martin van Buren         1837       1841  129.500000       Buren
8   William Henry Harrison         1841       1841  136.300000    Harrison
9               John Tyler         1841       1845  138.100000       Tyler
10              James Polk         1845       1849  133.400000        Polk
11          Zachary Taylor         1849       1850  129.800000      Taylor
12        Millard Fillmore         1850       1853  139.000000    Fillmore
13         Franklin Pierce         1853       1857  137.400000      Pierce
14          James Buchanan         1857       1861  129.600000    Buchanan
15         Abraham Lincoln         1861       1865  140.000000     Lincoln
16          Andrew Johnson         1865       1869  129.800000     Johnson
17           Ulysses Grant         1869       1877  120.000000       Grant
18        Rutherford Hayes         1877       1881  136.300000       Hayes
19          James Garfield         1881       1881  142.300000    Garfield
20          Chester Arthur         1881       1885  142.300000      Arthur
21        Grover Cleveland         1885       1897  134.000000   Cleveland
22       Benjamin Harrison         1889       1893  135.400000    Harrison
23        William McKinley         1897       1901  133.400000    McKinley
24      Theodore Roosevelt         1901       1909  143.000000   Roosevelt
25     William Howard Taft         1909       1913  129.500000        Taft
26          Woodrow Wilson         1913       1921  145.200000      Wilson
27          Warren Harding         1921       1923  129.900000     Harding
28         Calvin Coolidge         1923       1929  131.600000    Coolidge
29          Herbert Hoover         1929       1933  131.600000      Hoover
30      Franklin Roosevelt         1933       1945  130.500000   Roosevelt
31            Harry Truman         1945       1953  129.800000      Truman
32       Dwight Eisenhower         1953       1961  135.100000  Eisenhower
33         John F. Kennedy         1961       1963  134.400000     Kennedy
34          Lyndon Johnson         1963       1969  130.600000     Johnson
35           Richard Nixon         1969       1974  137.800000       Nixon
36             Gerald Ford         1974       1977  130.200000        Ford
37            Jimmy Carter         1977       1981  153.000000      Carter
38           Ronald Reagan         1981       1989  131.900000      Reagan
39       George H. W. Bush         1989       1993  133.000000        Bush
40            Bill Clinton         1993       2001  147.333333     Clinton
41          George W. Bush         2001       2009  131.650000        Bush
42            Barack Obama         2009       2017  137.500000       Obama
43            Donald Trump         2017        NaN         NaN       Trump

iqs_noname = iqs.drop('name',1)

In [215]:
convert_all_numcol_to_int(iqs)

                 full_name  office_start office_end          iq        name
0        George Washington          1789       1797  130.000000  Washington
1               John Adams          1797       1801  145.000000       Adams
2         Thomas Jefferson          1801       1809  150.000000   Jefferson
3            James Madison          1809       1817  150.000000     Madison
4             James Monroe          1817       1825  128.600000      Monroe
5        John Quincy Adams          1825       1829  165.000000       Adams
6           Andrew Jackson          1829       1837  135.000000     Jackson
7         Martin van Buren          1837       1841  129.500000       Buren
8   William Henry Harrison          1841       1841  136.300000    Harrison
9               John Tyler          1841       1845  138.100000       Tyler
10              James Polk          1845       1849  133.400000        Polk
11          Zachary Taylor          1849       1850  129.800000      Taylor
12        Millard Fillmore          1850       1853  139.000000    Fillmore
13         Franklin Pierce          1853       1857  137.400000      Pierce
14          James Buchanan          1857       1861  129.600000    Buchanan
15         Abraham Lincoln          1861       1865  140.000000     Lincoln
16          Andrew Johnson          1865       1869  129.800000     Johnson
17           Ulysses Grant          1869       1877  120.000000       Grant
18        Rutherford Hayes          1877       1881  136.300000       Hayes
19          James Garfield          1881       1881  142.300000    Garfield
20          Chester Arthur          1881       1885  142.300000      Arthur
21        Grover Cleveland          1885       1897  134.000000   Cleveland
22       Benjamin Harrison          1889       1893  135.400000    Harrison
23        William McKinley          1897       1901  133.400000    McKinley
24      Theodore Roosevelt          1901       1909  143.000000   Roosevelt
25     William Howard Taft          1909       1913  129.500000        Taft
26          Woodrow Wilson          1913       1921  145.200000      Wilson
27          Warren Harding          1921       1923  129.900000     Harding
28         Calvin Coolidge          1923       1929  131.600000    Coolidge
29          Herbert Hoover          1929       1933  131.600000      Hoover
30      Franklin Roosevelt          1933       1945  130.500000   Roosevelt
31            Harry Truman          1945       1953  129.800000      Truman
32       Dwight Eisenhower          1953       1961  135.100000  Eisenhower
33         John F. Kennedy          1961       1963  134.400000     Kennedy
34          Lyndon Johnson          1963       1969  130.600000     Johnson
35           Richard Nixon          1969       1974  137.800000       Nixon
36             Gerald Ford          1974       1977  130.200000        Ford
37            Jimmy Carter          1977       1981  153.000000      Carter
38           Ronald Reagan          1981       1989  131.900000      Reagan
39       George H. W. Bush          1989       1993  133.000000        Bush
40            Bill Clinton          1993       2001  147.333333     Clinton
41          George W. Bush          2001       2009  131.650000        Bush
42            Barack Obama          2009       2017  137.500000       Obama
43            Donald Trump          2017        NaN         NaN       Trump

In [216]:
iqs.dtypes

full_name        object
office_start      int32
office_end       object
iq              float64
name             object
dtype: object

### Merge inaug with iqs

In [219]:
inaug_iqs = pd.merge(inaug, iqs, left_on='year', right_on='office_start', how='left')
inaug_iqs

,in_number,year,length,words,sents,vocab,awl,asl,awps,avps,awpv,full_name,office_start,office_end,iq,name
0,0,1789,4705.0,842.50,14.00,349.50,5.492492,278.437500,50.416667,24.458333,2.046863,George Washington,1789.0,1797,130.000000,Washington
1,1,1797,13877.0,2585.00,37.00,803.00,5.368279,375.054054,69.864865,21.702703,3.219178,John Adams,1797.0,1801,145.000000,Adams
2,2,1801,11522.5,2159.50,43.50,735.00,5.326595,264.100794,49.524603,16.878571,2.930647,Thomas Jefferson,1801.0,1809,150.000000,Jefferson
3,3,1809,7079.0,1284.50,27.00,525.00,5.511442,275.129870,49.876623,20.463203,2.446746,James Madison,1809.0,1817,150.000000,Madison
4,4,1817,23106.5,4301.00,125.50,1100.00,5.373928,183.542858,34.162378,8.746632,3.894316,James Monroe,1817.0,1825,128.600000,Monroe
5,5,1825,17741.0,3150.00,74.00,972.00,5.632063,239.743243,42.567568,13.135135,3.240741,John Quincy Adams,1825.0,1829,165.000000,Adams
6,6,1829,6937.5,1237.50,27.50,493.00,5.606926,253.973333,45.276667,18.113333,2.512728,Andrew Jackson,1829.0,1837,135.000000,Jackson
7,7,1837,23417.0,4171.00,95.00,1267.00,5.614241,246.494737,43.905263,13.336842,3.292028,Martin van Buren,1837.0,1841,129.500000,Buren
8,8,1841,49700.0,9165.00,210.00,1813.00,5.422804,236.666667,43.642857,8.633333,5.055157,William Henry Harrison,1841.0,1841,136.300000,Harrison
9,8,1841,49700.0,9165.00,210.00,1813.00,5.422804,236.666667,43.642857,8.633333,5.055157,John Tyler,1841.0,1845,138.100000,Tyler
10,9,1845,28716.0,5196.00,153.00,1267.00,5.526559,187.686275,33.960784,8.281046,4.101026,James Polk,1845.0,1849,133.400000,Polk
11,10,1849,6605.0,1182.00,22.00,488.00,5.587986,300.227273,53.727273,22.181818,2.422131,Zachary Taylor,1849.0,1850,129.800000,Taylor
12,11,1853,20081.0,3657.00,104.00,1124.00,5.491113,193.086538,35.163462,10.807692,3.253559,Franklin Pierce,1853.0,1857,137.400000,Pierce
13,12,1857,16815.0,3098.00,89.00,902.00,5.427695,188.932584,34.808989,10.134831,3.434590,James Buchanan,1857.0,1861,129.600000,Buchanan
14,13,1861,12471.5,2395.00,82.50,682.00,5.124482,148.852254,29.047907,10.080918,3.102843,Abraham Lincoln,1861.0,1865,140.000000,Lincoln
15,14,1869,7118.5,1358.50,42.50,502.00,5.240667,167.191242,31.905211,11.803215,2.701302,Ulysses Grant,1869.0,1877,120.000000,Grant
16,15,1877,14938.0,2724.00,59.00,808.00,5.483847,253.186441,46.169492,13.694915,3.371287,Rutherford Hayes,1877.0,1881,136.300000,Hayes
17,16,1881,17767.0,3239.00,112.00,981.00,5.485335,158.633929,28.919643,8.758929,3.301733,James Garfield,1881.0,1881,142.300000,Garfield
18,16,1881,17767.0,3239.00,112.00,981.00,5.485335,158.633929,28.919643,8.758929,3.301733,Chester Arthur,1881.0,1885,142.300000,Arthur
19,17,1885,10145.0,1828.00,44.00,650.00,5.549781,230.568182,41.545455,14.772727,2.812308,Grover Cleveland,1885.0,1897,134.000000,Cleveland
20,18,1889,26179.0,4750.00,157.00,1313.00,5.511368,166.745223,30.254777,8.363057,3.617669,Benjamin Harrison,1889.0,1893,135.400000,Harrison
21,19,1893,12349.0,2153.00,58.00,799.00,5.735718,212.913793,37.120690,13.775862,2.694618,NaN,NaN,NaN,NaN,NaN
22,20,1897,18533.5,3410.50,115.00,1013.50,5.442687,158.036154,29.061538,8.751538,3.302238,William McKinley,1897.0,1901,133.400000,McKinley
23,21,1905,5568.0,1091.00,33.00,388.00,5.103575,168.727273,33.060606,11.757576,2.811856,NaN,NaN,NaN,NaN,NaN
24,22,1909,32164.0,5846.00,159.00,1385.00,5.501882,202.289308,36.767296,8.710692,4.220939,William Howard Taft,1909.0,1913,129.500000,Taft
25,23,1913,8979.0,1780.50,64.00,583.00,5.044696,140.274510,27.807353,9.092157,3.060508,Woodrow Wilson,1913.0,1921,145.200000,Wilson
26,24,1921,20298.0,3756.00,149.00,1126.00,5.404153,136.228188,25.208054,7.557047,3.335702,Warren Harding,1921.0,1923,129.900000,Harding
27,25,1925,23949.0,4442.00,197.00,1164.00,5.391490,121.568528,22.548223,5.908629,3.816151,NaN,NaN,NaN,NaN,NaN
28,26,1929,21764.0,3890.00,158.00,998.00,5.594859,137.746835,24.620253,6.316456,3.897796,Herbert Hoover,1929.0,1933,131.600000,Hoover
29,27,1933,8030.0,1563.75,68.75,546.25,5.059612,116.745756,23.097518,8.362392,2.799221,Franklin Roosevelt,1933.0,1945,130.500000,Roosevelt
30,28,1949,13679.0,2528.00,116.00,745.00,5.410997,117.922414,21.793103,6.422414,3.393289,NaN,NaN,NaN,NaN,NaN
31,29,1953,11572.5,2346.00,107.50,728.00,4.911389,106.673294,21.698966,6.729586,3.224991,Dwight Eisenhower,1953.0,1961,135.100000,Eisenhower
32,30,1961,7618.0,1546.00,52.00,546.00,4.927555,146.500000,29.730769,10.500000,2.831502,John F. Kennedy,1961.0,1963,134.400000,Kennedy
33,31,1965,8193.0,1715.00,94.00,538.00,4.777259,87.159574,18.244681,5.723404,3.187732,NaN,NaN,NaN,NaN,NaN
34,32,1969,10807.5,2226.50,87.50,615.00,4.859965,127.228739,26.134331,7.107055,3.663296,Richard Nixon,1969.0,1974,137.800000,Nixon
35,33,1977,6873.0,1380.00,53.00,504.00,4.980435,129.679245,26.037736,9.509434,2.738095,Jimmy Carter,1977.0,1981,153.000000,Carter
36,34,1981,14148.0,2873.50,126.50,865.50,4.923120,111.856549,22.718035,6.842332,3.319519,Ronald Reagan,1981.0,1989,131.900000,Reagan
37,35,1989,12523.0,2713.00,145.00,754.00,4.615923,86.365517,18.710345,5.200000,3.598143,George H. W. Bush,1989.0,1993,133.000000,Bush
38,36,1993,10682.0,2158.50,96.50,665.50,4.944419,110.946759,22.441689,6.973931,3.228856,Bill Clinton,1993.0,2001,147.333333,Clinton
39,37,2001,10535.5,2100.50,96.00,667.50,5.009314,109.917580,21.912480,6.961964,3.139864,George W. Bush,2001.0,2009,131.650000,Bush
40,38,2009,13439.0,2726.00,112.00,900.00,4.929934,119.991071,24.339286,8.035714,3.028889,Barack Obama,2009.0,2017,137.500000,Obama

In [140]:
len(inaug_iqs.name.unique())

35